# input_fasta: /s/genomes/Gencode/Gencode_human/release_40/GRCh38.primary_assembly.genome.fa
# # vep_dir: /s/raw/vep/112
# vep_plugin_dir: /s/raw/vep/112/Plugins
# genome_assembly: GRCh37
# vep_nfork: 5

# additional_vep_plugin_cmds:
#   cadd : CADD,/s/raw/cadd/v1.6/GRCh37/whole_genome_SNVs.tsv.gz,/s/raw/cadd/v1.6/GRCh37/InDels.tsv.gz
#   tss_distance : TSSDistance

# Example config for running VEP offline (with cached data)
# the paths `vep` and `vep_data` have to be adapted based on where the VEP cache
# and other vep relevant files have been stored
# See instruction on VEP how to set up the Cache and install plugins
# https://www.ensembl.org/info/docs/tools/vep/script/vep_cache.html#pre
offline: true
vep_nfork: 5
genome_assembly: GRCh37
species: homo_sapiens
pick_order: "biotype,canonical,appris,tsl,ccds,rank,length,ensembl,refseq"
additional_flags:
  - "--polyphen s"
  - "--sift s"
  - "--total_length"
  - "--total_length"
  - "--no_escape"
  - "--canonical"
  - "--protein"
  - "--biotype"
  - "--force_overwrite"
  - "--no_stats"
  - "--per_gene"

## these fields are only needed if offline = true
input_fasta: /s/genomes/Gencode/Gencode_human/release_40/GRCh38.primary_assembly.genome.fa
cache_dir: /s/raw/vep/112
vep_plugin_dir: /s/raw/vep/112/Plugins
af_flags: --af_gnomad

additional_vep_plugin_cmds:
  cadd: CADD,/s/raw/cadd/v1.6/GRCh37/whole_genome_SNVs.tsv.gz,/s/raw/cadd/v1.6/GRCh37/InDels.tsv.gz
  tss_distance: TSSDistance
