root: /home/lollo/Work/hackathon/data/Yazar_OneK1K
scdata_path: ${root}/debug_OneK1K_cohort_gene_expression_matrix_14_celltypes.h5ad
annotation_path: ${root}/gene_annotation.csv
gdata_path: ${root}/OneK1K_imputation_post_qc_r2_08/plink/
dump_path: /home/lollo/Work/hackathon/out/dumps
