scdata_path: /lustre/groups/shared/scgenetics/onek1k/rna/OneK1K_cohort_gene_expression_matrix_14_celltypes.h5ad.gz
annotation_path: /lustre/groups/shared/scgenetics/onek1k/metadata/gene_annotation.csv
gdata_path: /lustre/groups/shared/scgenetics/onek1k/genotypes_OneK1K_imputation_post_qc_r2_08/plink/
dump_path: /lustre/groups/ml01/workspace/lorenzo.consoli/output/sc-genetics/
