root: /lustre/groups/shared/scgenetics/onek1k
scdata_path:  ${root}/rna/OneK1K_cohort_gene_expression_matrix_14_celltypes.h5ad.gz
annotation_path:  ${root}/metadata/gene_annotation.csv
gdata_path:  ${root}/genotypes_OneK1K_imputation_post_qc_r2_08/plink/
dump_path: /lustre/groups/ml01/workspace/lorenzo.consoli/output/sc-genetics/
