favor:
  essential:
    1: https://dataverse.harvard.edu/api/access/datafile/6170506
    2: https://dataverse.harvard.edu/api/access/datafile/6170501
    3: https://dataverse.harvard.edu/api/access/datafile/6170502
    4: https://dataverse.harvard.edu/api/access/datafile/6170521
    5: https://dataverse.harvard.edu/api/access/datafile/6170511
    6: https://dataverse.harvard.edu/api/access/datafile/6170516
    7: https://dataverse.harvard.edu/api/access/datafile/6170505
    8: https://dataverse.harvard.edu/api/access/datafile/6170513
    9: https://dataverse.harvard.edu/api/access/datafile/6165867
    10: https://dataverse.harvard.edu/api/access/datafile/6170507
    11: https://dataverse.harvard.edu/api/access/datafile/6170517
    12: https://dataverse.harvard.edu/api/access/datafile/6170520
    13: https://dataverse.harvard.edu/api/access/datafile/6170503
    14: https://dataverse.harvard.edu/api/access/datafile/6170509
    15: https://dataverse.harvard.edu/api/access/datafile/6170515
    16: https://dataverse.harvard.edu/api/access/datafile/6170518
    17: https://dataverse.harvard.edu/api/access/datafile/6170510
    18: https://dataverse.harvard.edu/api/access/datafile/6170508
    19: https://dataverse.harvard.edu/api/access/datafile/6170514
    20: https://dataverse.harvard.edu/api/access/datafile/6170512
    21: https://dataverse.harvard.edu/api/access/datafile/6170519
    22: https://dataverse.harvard.edu/api/access/datafile/6170504
  full:
    1: https://dataverse.harvard.edu/api/access/datafile/6380374
    2: https://dataverse.harvard.edu/api/access/datafile/6380471
    3: https://dataverse.harvard.edu/api/access/datafile/6380732
    4: https://dataverse.harvard.edu/api/access/datafile/6381512
    5: https://dataverse.harvard.edu/api/access/datafile/6381457
    6: https://dataverse.harvard.edu/api/access/datafile/6381327
    7: https://dataverse.harvard.edu/api/access/datafile/6384125
    8: https://dataverse.harvard.edu/api/access/datafile/6382573
    9: https://dataverse.harvard.edu/api/access/datafile/6384268
    10: https://dataverse.harvard.edu/api/access/datafile/6380273
    11: https://dataverse.harvard.edu/api/access/datafile/6384154
    12: https://dataverse.harvard.edu/api/access/datafile/6384198
    13: https://dataverse.harvard.edu/api/access/datafile/6388366
    14: https://dataverse.harvard.edu/api/access/datafile/6388406
    15: https://dataverse.harvard.edu/api/access/datafile/6388427
    16: https://dataverse.harvard.edu/api/access/datafile/6388551
    17: https://dataverse.harvard.edu/api/access/datafile/6388894
    18: https://dataverse.harvard.edu/api/access/datafile/6376523
    19: https://dataverse.harvard.edu/api/access/datafile/6376522
    20: https://dataverse.harvard.edu/api/access/datafile/6376521
    21: https://dataverse.harvard.edu/api/access/datafile/6358305
    22: https://dataverse.harvard.edu/api/access/datafile/6358299
